### ISSUE TITLE
Error: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by eightysteele** [tryfabric/notion-github-action#62]
### Describe the bug

Using `tryfabric/notion-github-action@v1.2.1`, creating a new GH issue fails to sync to Notion via the workflow action.

### Steps to reproduce

1. Follow the setup
2. Create a new issue
3. Check the failed action

### Expected behavior

A new Notion page created for the GH issue.

### Additional context

This recently started failing. I upgraded to `tryfabric/notion-github-action@v1.2.1` but it's still failing. Any sense for what might be going on? Thanks. :)

<img width="459" alt="Screen Shot 2022-07-20 at 1 27 29 PM" src="https://user-images.githubusercontent.com/462255/180075588-239af9f1-b842-488a-96a1-77ce3d1be9de.png">

**Comment by markleung0905** [comment]
I'm having the same problem.

**Comment by eightysteele** [comment]
👋🏻 hello friends, curious if any updates on this one. thanks! :)

**Comment by PanicBear** [comment]
## If I may, this problem would be solved with modifying value of argument!

- src/action.ts line 112
  - ASIS: function getBodyChildrenBlocks(body: string)
  - TODO: function getBodyChildrenBlocks(**_body?: string_**)

## Reason I Think!
1.  As I tested, this problem occurs when content of question is empty.
Not comments only body of issues; we cannot post comment empty.
<img width="920" alt="스크린샷 2022-08-09 오전 10 43 03" src="https://user-images.githubusercontent.com/64050117/183544571-31d76b60-cdb1-479a-ac11-caad8d387fc1.png">

2. Before error shows up, I found this log printed. 
```Querying database for page with github id...``` 
<img width="514" alt="스크린샷 2022-08-09 오전 10 44 51" src="https://user-images.githubusercontent.com/64050117/183544778-6cc46c22-eda2-4f9f-83ef-a984d4293ec5.png">

3. There was single function, this log is written. 
```
// src/action.ts Line 162
async function handleIssueEdited(options: IssueEditedOptions) {
  const {notion, payload, octokit} = options;

  core.info(`Querying database for page with github id ${payload.issue.id}`);

  const query = await notion.client.databases.query({
    database_id: notion.databaseId,
    filter: {
      property: 'ID',
      number: {
        equals: payload.issue.id,
      },
    },
    page_size: 1,
  });

  const bodyBlocks = getBodyChildrenBlocks(payload.issue.body);
```
4. And there was function right below this log, receiving content of body as string. 
```
function getBodyChildrenBlocks(body: string): Exclude<CreatePageParameters['children'], undefined> {
  // We're currently using only one paragraph block, but this could be extended to multiple kinds of blocks.
  return [
    {
      type: 'paragraph',
      paragraph: {
        text: parseBodyRichText(body),
      },
    },
  ];
}
```
---
This is my first comment of github community, 
so I hope you don't get mad if it doesn't work..

**Comment by PanicBear** [comment]
@EndBug Would you kindly considerate upper comment?

**Comment by EndBug** [comment]
Hi @PanicBear
Fabric has closed, and so there is no staff doing active maintenance on these repos.
If you have any changes you'd like to see in the action, feel free to fork and test them on your own. If they work you're welcome to open a PR and tag me there, I'll take a look ;)

**Comment by eightysteele** [comment]
sorry to hear that fabric closed! for those following along, the latest version of notion supports syncing with github: https://www.notion.so/help/guides/synced-databases-bridge-different-tools
